In [1]:
import pandas as pd
data=pd.read_csv("tweetdataexcel.csv")

In [2]:
data

Tweets
0        is upset that he can't update his Facebook by ...
1        @Kenichan I dived many times for the ball. Man...
2          my whole body feels itchy and like its on fire 
3        @nationwideclass no, it's not behaving at all....
4                            @Kwesidei not the whole crew 
...                                                    ...
1048570           My GrandMa is making Dinenr with my Mum 
1048571  Mid-morning snack time... A bowl of cheese noo...
1048572  @ShaDeLa same here  say it like from the Termi...
1048573             @DestinyHope92 im great thaanks  wbuu?
1048574               cant wait til her date this weekend 

[1048575 rows x 1 columns]

In [3]:
data['Tweets']

0          is upset that he can't update his Facebook by ...
1          @Kenichan I dived many times for the ball. Man...
2            my whole body feels itchy and like its on fire 
3          @nationwideclass no, it's not behaving at all....
4                              @Kwesidei not the whole crew 
                                 ...                        
1048570             My GrandMa is making Dinenr with my Mum 
1048571    Mid-morning snack time... A bowl of cheese noo...
1048572    @ShaDeLa same here  say it like from the Termi...
1048573               @DestinyHope92 im great thaanks  wbuu?
1048574                 cant wait til her date this weekend 
Name: Tweets, Length: 1048575, dtype: object

In [4]:
type(data)

pandas.core.frame.DataFrame

Making the tweets single line

In [5]:
tweets=[]
for i in range(0, 1048574):
  r=[]
  r1=data['Tweets'][i]
  r=r1.split("(")
  del r[-1]
  tweets.extend(r)

In [6]:
tweets

['@MissXu sorry! bed time came here ',
 "@ashleyac My donkey is sensitive about such comments. Nevertheless, he'd ",
 'Poor cameron ',
 "@stustone Your show is whack. Way worse than whack, it's wiggety-whack.    :*",
 ':*',
 ':*',
 'feeling lost, naked and confused ',
 '@DiannePulham OOOOOOOO who with? ',
 'http://twitpic.com/2y2wr - according to my bro, our new puppy had a poo fight and was covered in poop  ',
 '@amber_benson  my hubby ',
 'Scratch that: du in heif ',
 '@Sara_Kate Im afraid too  ',
 'Any chance  Softbelly ',
 'http://is.gd/r8Zf,  http://is.gd/r8Zy, and  http://is.gd/r8ZG - test footage with my girlfriend ',
 "wishes for good old cartoons to come back. ie: Captain Planet! Where's Wally! Daria! ",
 "@Torturedlady yea  ma'naaaaaaaaaaaaaaaaaaaam ",
 'I accessed oneindia.mobi from a Google phone ',
 "is stucked in Paris and can't even travel into France ",
 'My 4 year old ',
 'happy for Coach Stringer ',
 "There's an inch of snow on the ground ",
 '@transbay &quot;SFMTA Bu

Removing special chars and converting to meaningful lines    


In [7]:
import re

for i in range(len(tweets)):
  s=tweets[i]
  m=re.search("@",s)
  if(m):
    s=s[(m.end()+4):]
  
  s=re.sub("(n\'t)|(\w+nt)"," not",s)
  s=re.sub("(\'ve)"," have",s)
  s=re.sub("(\'s)"," is",s)
  s=re.sub("(\'m)"," am",s)
  s=re.sub("\\\\n","  ",s)
  s=re.sub(".\\\\.","  ",s)
  s=re.sub("\\\\.","  ",s)
  s=re.sub("\\\\x","  ",s)
  s=re.sub("x8","  ",s)
  s=re.sub('[^a-zA-Z]',' ',s)

  tweets[i]=s

In [8]:
tweets

['Xu sorry  bed time came here ',
 'eyac My donkey is sensitive about such  nots  Nevertheless  he d ',
 'Poor cameron ',
 'tone Your show is whack  Way worse than whack  it is wiggety whack       ',
 '  ',
 '  ',
 'feeling lost  naked and confused ',
 'nePulham OOOOOOOO who with  ',
 'http   twitpic com  y wr   according to my bro  our new puppy had a poo fight and was covered in poop  ',
 'r benson  my hubby ',
 'Scratch that  du in heif ',
 ' Kate Im afraid too  ',
 'Any chance  Softbelly ',
 'http   is gd r Zf   http   is gd r Zy  and  http   is gd r ZG   test footage with my girlfriend ',
 'wishes for good old cartoons to come back  ie  Captain Planet  Where is Wally  Daria  ',
 'uredlady yea  ma naaaaaaaaaaaaaaaaaaaam ',
 'I accessed oneindia mobi from a Google phone ',
 'is stucked in Paris and ca not even travel  noto France ',
 'My   year old ',
 'happy for Coach Stringer ',
 'There is an inch of snow on the ground ',
 'sbay  quot SFMTA Budget Proposal Hearing  tomorrow  April

In [9]:
while '' in tweets:
    tweets.remove('')

In [10]:
tweets

['Xu sorry  bed time came here ',
 'eyac My donkey is sensitive about such  nots  Nevertheless  he d ',
 'Poor cameron ',
 'tone Your show is whack  Way worse than whack  it is wiggety whack       ',
 '  ',
 '  ',
 'feeling lost  naked and confused ',
 'nePulham OOOOOOOO who with  ',
 'http   twitpic com  y wr   according to my bro  our new puppy had a poo fight and was covered in poop  ',
 'r benson  my hubby ',
 'Scratch that  du in heif ',
 ' Kate Im afraid too  ',
 'Any chance  Softbelly ',
 'http   is gd r Zf   http   is gd r Zy  and  http   is gd r ZG   test footage with my girlfriend ',
 'wishes for good old cartoons to come back  ie  Captain Planet  Where is Wally  Daria  ',
 'uredlady yea  ma naaaaaaaaaaaaaaaaaaaam ',
 'I accessed oneindia mobi from a Google phone ',
 'is stucked in Paris and ca not even travel  noto France ',
 'My   year old ',
 'happy for Coach Stringer ',
 'There is an inch of snow on the ground ',
 'sbay  quot SFMTA Budget Proposal Hearing  tomorrow  April

In [11]:
from pandas import DataFrame

df = DataFrame (tweets,columns=['tweets'])

In [12]:
df

tweets
0                          Xu sorry  bed time came here 
1      eyac My donkey is sensitive about such  nots  ...
2                                          Poor cameron 
3      tone Your show is whack  Way worse than whack ...
4                                                       
...                                                  ...
25332  docia     I think the answer to    is the fact...
25333  gotta pack up    move to my moms this weekend ...
25334  a  StanSmithCIA  sarahdiddle  SpitfireJon  pon...
25335  raig Thanks   Bless  Enjoy the innocence  The ...
25336   followfriday because he is as sick in the hea...

[25337 rows x 1 columns]

In [13]:
df.isnull()

tweets
0       False
1       False
2       False
3       False
4       False
...       ...
25332   False
25333   False
25334   False
25335   False
25336   False

[25337 rows x 1 columns]

In [ ]:
df.any()

In [15]:
import nltk

nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\Shazmeen\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!


True

In [16]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
sia = SentimentIntensityAnalyzer()
df['scores']=df['tweets'].apply(lambda tweets : sia.polarity_scores(tweets))

In [17]:
df

tweets  \
0                          Xu sorry  bed time came here    
1      eyac My donkey is sensitive about such  nots  ...   
2                                          Poor cameron    
3      tone Your show is whack  Way worse than whack ...   
4                                                          
...                                                  ...   
25332  docia     I think the answer to    is the fact...   
25333  gotta pack up    move to my moms this weekend ...   
25334  a  StanSmithCIA  sarahdiddle  SpitfireJon  pon...   
25335  raig Thanks   Bless  Enjoy the innocence  The ...   
25336   followfriday because he is as sick in the hea...   

                                                  scores  
0      {'neg': 0.206, 'neu': 0.794, 'pos': 0.0, 'comp...  
1      {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...  
2      {'neg': 0.756, 'neu': 0.244, 'pos': 0.0, 'comp...  
3      {'neg': 0.205, 'neu': 0.795, 'pos': 0.0, 'comp...  
4      {'neg': 0.0, 'neu': 0.0, 'pos': 0.0, 'compound...  
...                                                  ...  
25332  {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...  
25333  {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...  
25334  {'neg': 0.0, 'neu': 0.756, 'pos': 0.244, 'comp...  
25335  {'neg': 0.0, 'neu': 0.549, 'pos': 0.451, 'comp...  
25336  {'neg': 0.248, 'neu': 0.752, 'pos': 0.0, 'comp...  

[25337 rows x 2 columns]

In [18]:
df['compound']=df['scores'].apply(lambda score_dict : score_dict['compound'])

In [19]:
df

tweets  \
0                          Xu sorry  bed time came here    
1      eyac My donkey is sensitive about such  nots  ...   
2                                          Poor cameron    
3      tone Your show is whack  Way worse than whack ...   
4                                                          
...                                                  ...   
25332  docia     I think the answer to    is the fact...   
25333  gotta pack up    move to my moms this weekend ...   
25334  a  StanSmithCIA  sarahdiddle  SpitfireJon  pon...   
25335  raig Thanks   Bless  Enjoy the innocence  The ...   
25336   followfriday because he is as sick in the hea...   

                                                  scores  compound  
0      {'neg': 0.206, 'neu': 0.794, 'pos': 0.0, 'comp...   -0.0772  
1      {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...    0.0000  
2      {'neg': 0.756, 'neu': 0.244, 'pos': 0.0, 'comp...   -0.4767  
3      {'neg': 0.205, 'neu': 0.795, 'pos': 0.0, 'comp...   -0.4767  
4      {'neg': 0.0, 'neu': 0.0, 'pos': 0.0, 'compound...    0.0000  
...                                                  ...       ...  
25332  {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...    0.0000  
25333  {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...    0.0000  
25334  {'neg': 0.0, 'neu': 0.756, 'pos': 0.244, 'comp...    0.4404  
25335  {'neg': 0.0, 'neu': 0.549, 'pos': 0.451, 'comp...    0.8885  
25336  {'neg': 0.248, 'neu': 0.752, 'pos': 0.0, 'comp...   -0.5106  

[25337 rows x 3 columns]

In [20]:
lbl=[]
for i in range(25337):
  l=df.loc[i]['scores']
  del l['compound']
  lbl.extend(l)

In [21]:
l2=df.loc[25336]['scores']
l2

{'neg': 0.248, 'neu': 0.752, 'pos': 0.0}

In [22]:
m=max(l2,key=l2.get)
print(m)

neu


In [23]:
df['label']=df['scores'].apply(lambda c : max(c,key=c.get))

In [24]:
df

tweets  \
0                          Xu sorry  bed time came here    
1      eyac My donkey is sensitive about such  nots  ...   
2                                          Poor cameron    
3      tone Your show is whack  Way worse than whack ...   
4                                                          
...                                                  ...   
25332  docia     I think the answer to    is the fact...   
25333  gotta pack up    move to my moms this weekend ...   
25334  a  StanSmithCIA  sarahdiddle  SpitfireJon  pon...   
25335  raig Thanks   Bless  Enjoy the innocence  The ...   
25336   followfriday because he is as sick in the hea...   

                                         scores  compound label  
0      {'neg': 0.206, 'neu': 0.794, 'pos': 0.0}   -0.0772   neu  
1          {'neg': 0.0, 'neu': 1.0, 'pos': 0.0}    0.0000   neu  
2      {'neg': 0.756, 'neu': 0.244, 'pos': 0.0}   -0.4767   neg  
3      {'neg': 0.205, 'neu': 0.795, 'pos': 0.0}   -0.4767   neu  
4          {'neg': 0.0, 'neu': 0.0, 'pos': 0.0}    0.0000   neg  
...                                         ...       ...   ...  
25332      {'neg': 0.0, 'neu': 1.0, 'pos': 0.0}    0.0000   neu  
25333      {'neg': 0.0, 'neu': 1.0, 'pos': 0.0}    0.0000   neu  
25334  {'neg': 0.0, 'neu': 0.756, 'pos': 0.244}    0.4404   neu  
25335  {'neg': 0.0, 'neu': 0.549, 'pos': 0.451}    0.8885   neu  
25336  {'neg': 0.248, 'neu': 0.752, 'pos': 0.0}   -0.5106   neu  

[25337 rows x 4 columns]

In [25]:
mydataset2=df
df2=mydataset2.drop(["scores","compound"],axis=1)

In [26]:
df2

tweets label
0                          Xu sorry  bed time came here    neu
1      eyac My donkey is sensitive about such  nots  ...   neu
2                                          Poor cameron    neg
3      tone Your show is whack  Way worse than whack ...   neu
4                                                          neg
...                                                  ...   ...
25332  docia     I think the answer to    is the fact...   neu
25333  gotta pack up    move to my moms this weekend ...   neu
25334  a  StanSmithCIA  sarahdiddle  SpitfireJon  pon...   neu
25335  raig Thanks   Bless  Enjoy the innocence  The ...   neu
25336   followfriday because he is as sick in the hea...   neu

[25337 rows x 2 columns]

In [27]:
df2.to_csv("tweets25337_dataset")

In [28]:
sampleData=df2[0:50000]

In [29]:
sampleData

tweets label
0                          Xu sorry  bed time came here    neu
1      eyac My donkey is sensitive about such  nots  ...   neu
2                                          Poor cameron    neg
3      tone Your show is whack  Way worse than whack ...   neu
4                                                          neg
...                                                  ...   ...
25332  docia     I think the answer to    is the fact...   neu
25333  gotta pack up    move to my moms this weekend ...   neu
25334  a  StanSmithCIA  sarahdiddle  SpitfireJon  pon...   neu
25335  raig Thanks   Bless  Enjoy the innocence  The ...   neu
25336   followfriday because he is as sick in the hea...   neu

[25337 rows x 2 columns]

In [30]:
sampleData['label'].value_counts()

neu    22659
pos     1397
neg     1281
Name: label, dtype: int64

In [31]:
sampleData.to_csv("tweets25337_dataset.csv")

In [32]:
sample

tweets label
0                          Xu sorry  bed time came here    neu
1      eyac My donkey is sensitive about such  nots  ...   neu
2                                          Poor cameron    neg
3      tone Your show is whack  Way worse than whack ...   neu
4                                                          neg
...                                                  ...   ...
25332  docia     I think the answer to    is the fact...   neu
25333  gotta pack up    move to my moms this weekend ...   neu
25334  a  StanSmithCIA  sarahdiddle  SpitfireJon  pon...   neu
25335  raig Thanks   Bless  Enjoy the innocence  The ...   neu
25336   followfriday because he is as sick in the hea...   neu

[25337 rows x 2 columns]

In [72]:
pd.set_option('display.max_rows', 500)

In [33]:
import re
import nltk

nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Shazmeen\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [34]:
c=[]
for i in range(0,25337):
    tweet = re.sub('[^a-zA-Z]', ' ', sampleData['tweets'][i])
    tweet=tweet.lower()
    tweet=tweet.split()
    tweet = [word for word in tweet if not word in set(stopwords.words('english'))]
    
    #applystemming concept
    ps = PorterStemmer()
    tweet = [ps.stem(word) for word in tweet if not word in set(stopwords.words('english'))]

    tweet=' '.join(tweet)
    c.append(tweet)


In [35]:
c

['xu sorri bed time came',
 'eyac donkey sensit not nevertheless',
 'poor cameron',
 'tone show whack way wors whack wiggeti whack',
 '',
 '',
 'feel lost nake confus',
 'nepulham oooooooo',
 'http twitpic com wr accord bro new puppi poo fight cover poop',
 'r benson hubbi',
 'scratch du heif',
 'kate im afraid',
 'chanc softbelli',
 'http gd r zf http gd r zy http gd r zg test footag girlfriend',
 'wish good old cartoon come back ie captain planet walli daria',
 'uredladi yea naaaaaaaaaaaaaaaaaaaam',
 'access oneindia mobi googl phone',
 'stuck pari ca even travel noto franc',
 'year old',
 'happi coach stringer',
 'inch snow ground',
 'sbay quot sfmta budget propos hear tomorrow april pm',
 'sigh rain decid show move away invit tuesday parti',
 'enb back',
 'uh feel lone wish bffwiamc',
 'today episod quot hous quot',
 'whf scc kill derek rees',
 'tri fix hubbi comput come disk window key wo work might buy',
 'ask friend piglet',
 'ett marissatast sad hous episod tonight bigger amp b

In [36]:
labels=[]
for i in range(0,25337):
    tweet = re.sub('[^a-zA-Z]', ' ', sampleData['label'][i])
    labels.append(tweet)

In [37]:
len(labels)

25337

In [38]:
labels

['neu',
 'neu',
 'neg',
 'neu',
 'neg',
 'neg',
 'neg',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'pos',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neg',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neg',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neg',
 'pos',
 'neg',
 'pos',
 'neu',
 'neu',
 'pos',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neg',
 'neg',
 'neg',
 'neg',
 'neu',
 'neu',
 'neg',
 'neu',
 'pos',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'pos',
 'neu',
 'neu',
 'neg',
 'neg',
 'neu',
 'neg',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neg',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neu',
 'neg',
 'neu',
 'neu',
 'neu',
 'neu',
 'pos',
 'neu',


In [41]:
import csv
with open('tweets25337_tweets.csv', 'w') as myfile:
  wr = csv.writer(myfile, quoting=csv.QUOTE_ALL)
  wr.writerow(c)

In [42]:
import csv
with open('tweets25337_labels.csv', 'w') as myfile:
  wr = csv.writer(myfile, quoting=csv.QUOTE_ALL)
  wr.writerow(labels)

In [43]:
import csv
with open('tweets25337_dataset.csv', 'w') as myfile:
  wr = csv.writer(myfile, quoting=csv.QUOTE_ALL)
  wr.writerow(sampleData)

In [44]:
len(c)

25337

In [45]:
c

['xu sorri bed time came',
 'eyac donkey sensit not nevertheless',
 'poor cameron',
 'tone show whack way wors whack wiggeti whack',
 '',
 '',
 'feel lost nake confus',
 'nepulham oooooooo',
 'http twitpic com wr accord bro new puppi poo fight cover poop',
 'r benson hubbi',
 'scratch du heif',
 'kate im afraid',
 'chanc softbelli',
 'http gd r zf http gd r zy http gd r zg test footag girlfriend',
 'wish good old cartoon come back ie captain planet walli daria',
 'uredladi yea naaaaaaaaaaaaaaaaaaaam',
 'access oneindia mobi googl phone',
 'stuck pari ca even travel noto franc',
 'year old',
 'happi coach stringer',
 'inch snow ground',
 'sbay quot sfmta budget propos hear tomorrow april pm',
 'sigh rain decid show move away invit tuesday parti',
 'enb back',
 'uh feel lone wish bffwiamc',
 'today episod quot hous quot',
 'whf scc kill derek rees',
 'tri fix hubbi comput come disk window key wo work might buy',
 'ask friend piglet',
 'ett marissatast sad hous episod tonight bigger amp b

In [46]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=1500)
x=cv.fit_transform(c).toarray()

In [47]:
sampleData

tweets label
0                          Xu sorry  bed time came here    neu
1      eyac My donkey is sensitive about such  nots  ...   neu
2                                          Poor cameron    neg
3      tone Your show is whack  Way worse than whack ...   neu
4                                                          neg
...                                                  ...   ...
25332  docia     I think the answer to    is the fact...   neu
25333  gotta pack up    move to my moms this weekend ...   neu
25334  a  StanSmithCIA  sarahdiddle  SpitfireJon  pon...   neu
25335  raig Thanks   Bless  Enjoy the innocence  The ...   neu
25336   followfriday because he is as sick in the hea...   neu

[25337 rows x 2 columns]

In [74]:
sampleData

tweets label
0                          Xu sorry  bed time came here    neu
1      eyac My donkey is sensitive about such  nots  ...   neu
2                                          Poor cameron    neg
3      tone Your show is whack  Way worse than whack ...   neu
4                                                          neg
...                                                  ...   ...
25332  docia     I think the answer to    is the fact...   neu
25333  gotta pack up    move to my moms this weekend ...   neu
25334  a  StanSmithCIA  sarahdiddle  SpitfireJon  pon...   neu
25335  raig Thanks   Bless  Enjoy the innocence  The ...   neu
25336   followfriday because he is as sick in the hea...   neu

[25337 rows x 2 columns]

In [75]:
pd.set_option('display.max_rows', 500)

In [76]:
sampleData

tweets label
0                          Xu sorry  bed time came here    neu
1      eyac My donkey is sensitive about such  nots  ...   neu
2                                          Poor cameron    neg
3      tone Your show is whack  Way worse than whack ...   neu
4                                                          neg
...                                                  ...   ...
25332  docia     I think the answer to    is the fact...   neu
25333  gotta pack up    move to my moms this weekend ...   neu
25334  a  StanSmithCIA  sarahdiddle  SpitfireJon  pon...   neu
25335  raig Thanks   Bless  Enjoy the innocence  The ...   neu
25336   followfriday because he is as sick in the hea...   neu

[25337 rows x 2 columns]

In [48]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [51]:
y=sampleData.iloc[:,-1].values

In [52]:
y

array(['neu', 'neu', 'neg', ..., 'neu', 'neu', 'neu'], dtype=object)

In [53]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

y=lb.fit_transform(y)

In [54]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2, random_state=0)

In [55]:
import keras 
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.
C:\Users\Shazmeen\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Shazmeen\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Shazmeen\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Shazmeen\anaconda3\lib\site-packages\tensorflow\python\framewo

In [56]:
x_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [57]:
y_train

array([1, 1, 1, ..., 0, 1, 1])

In [58]:
model = Sequential()
model.add(Dense(input_dim=1500, init="random_uniform", activation='sigmoid',output_dim=1000))
model.add(Dense(output_dim=1000, init="random_uniform", activation='sigmoid'))
model.add(Dense(output_dim=3, init="random_uniform", activation='softmax'))
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(x_train,y_train, epochs=10, batch_size=10)

C:\Users\Shazmeen\anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=1500, activation="sigmoid", units=1000, kernel_initializer="random_uniform")`
  
C:\Users\Shazmeen\anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1000, kernel_initializer="random_uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Shazmeen\anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="softmax", units=3, kernel_initializer="random_uniform")`
  after removing the cwd from sys.path.


Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

Epoch 1/10
20269/20269 [==============================] - 123s 6ms/step - loss: 0.3603 - acc: 0.8954
Epoch 2/10
20269/20269 [==============================] - 117s 6ms/step - loss: 0.2844 - acc: 0.9017
Epoch 3/10
20269/20269 [==============================] - 119s 6ms/step - loss: 0.2489 - acc: 0.9083 1s - loss: - ETA: 0s - loss: 0.2489 -
Epoch 4/10
20269/20269 [==============================] - 118s 6ms/step - loss: 0.2138 - acc: 0.9179 1s - loss: 
Epoch 5/10
20269/20269 [==============================] - 116s 6ms/step - loss: 0.2002 - acc: 0.9215
Epoch 6/10
20269/20269 [==============================] - 116s 6ms/step - loss: 0.1922 - acc: 0.9248
Epoch 7/10
20269/20269 [==============================] - 118s 6ms/step - loss: 0.1890 - acc: 0.9252 2s - loss: 0.1895 - acc: 0.9 - ETA: 0s - loss: 0.1890 - acc: 0.
Epoch 8/10
20269/20269 [==============================] - 117s 6ms/step - loss: 0.18

In [60]:
x_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [61]:
y_pred=model.predict(x_test)
y_pred

array([[2.5585731e-02, 9.6233147e-01, 1.2082732e-02],
       [2.5259359e-03, 9.9568474e-01, 1.7892974e-03],
       [4.2219901e-01, 5.7419926e-01, 3.6017022e-03],
       ...,
       [6.2966280e-02, 8.6965257e-01, 6.7381129e-02],
       [2.7739286e-04, 9.9736387e-01, 2.3587435e-03],
       [3.8969722e-01, 6.0638821e-01, 3.9146584e-03]], dtype=float32)

In [62]:
y_train

array([1, 1, 1, ..., 0, 1, 1])

In [67]:
y_pred.all

<function bool_.all>

In [68]:
y_pred=y_pred.all()
y_pred

True

In [69]:
model.save("NLPtweetmodel.h5")

In [70]:
import pickle

filename = 'nlp_tweets_model.pkl'
pickle.dump(model, open(filename, 'wb'))

In [71]:
pickle.dump(cv, open('cv_tranform.pkl', 'wb'))